[Flutter] Create reference implementation for Liquid SDK connection manager, event & log stream handler
breez/breez-liquid-sdk pull request #305
Opened 2024-06-10 14:05 UTC by erdemyerebasmaz

This PR addresses
- https://github.com/breez/breez-liquid-sdk/issues/260
- https://github.com/breez/breez-liquid-sdk/issues/264

`BreezLiquidSDK` wrapper class is introduced to handle stream subscription management similar to `BreezSDK`.
- Log stream should be subscribed early by on calling `BreezLiquidSDK.initializeLogStream()` on Dart entrypoint file of applications.
- Event stream subscription will be handle automatically on connecting to wallet.

Although most wallet API's are accessible through importing `'package:breez_liquid/breez_liquid.dart'`, they should be called via `BreezLiquidSDK.wallet` on application layer.

An internal helper method, `_fetchWalletData()`, is added to fetch wallet info and payment list when needed, _e.g.; after connecting to wallet & payments succeed etc._

#### Other changes:
- Direct use of `connect` & `disconnect` is hidden from end-user, only end-points are through `BreezLiquidSDK` wrapper.
- Logs on SDK event handler are added for debugging purposes at this stage of development. They will be removed.
- Updated example app

2024-06-10 14:30 UTC, roeierez requested changes

2024-06-10 14:45 UTC, erdemyerebasmaz commented on packages/flutter/lib/flutter_breez_liquid.dart
> +    _breezEventsStream ??= sdk.addEventListener().asBroadcastStream();
I prefer it that way too and not very fond of this approach but stream handling, wallet management etc. almost all this responsibility will lie on end-user, which I think will cause more headache than anything. This streamlines that process.

2024-06-12 09:39 UTC, erdemyerebasmaz commented on packages/flutter/lib/flutter_breez_liquid.dart
> +    _breezEventsStream ??= sdk.addEventListener().asBroadcastStream();
@roeierez Stream & wallet connection management is removed from Flutter plugin and is moved to example app as a reference, which we can improve upon and optimize later.

2024-06-13 11:51 UTC, dangeross approved these changes

2024-06-13 11:51 UTC, merged